import React from "react";
import { PlayCircle, ShieldCheck } from "lucide-react";
import { Button } from "../ui/Button.jsx";
import { PageHero } from "../ui/PageHero.jsx";

/**
 * Page introduction for Benchmarking.
 *
 * It keeps the page purpose clear and avoids the dense banner treatment from
 * the reference so users reach the analysis faster.
 */
export function BenchmarkingHero() {
  return (
    <PageHero
      eyebrow="Benchmarking"
      title="Benchmarking"
      titleId="benchmarking-title"
      description="Compare cost, schedule, progress and risk across sectors, ministries and peer projects to identify outliers."
      tone="saffron"
    >
      <div className="grid min-w-0 gap-3 lg:w-[430px]">
        <Button type="button" variant="secondary" className="w-full justify-center lg:w-fit">
          <PlayCircle className="size-4" aria-hidden="true" />
          How Benchmarking Works
        </Button>
        <aside className="rounded-md border border-[#c9d6e2] border-l-4 border-l-[#d97706] bg-white/90 p-4">
          <div className="grid gap-3 sm:grid-cols-[40px_1fr]">
            <span className="grid size-10 place-items-center rounded-md bg-[#ecfdf3] text-[#166534]">
            <ShieldCheck className="size-5" aria-hidden="true" />
            </span>
            <div className="min-w-0">
              <strong className="block text-sm font-black text-[#0b2545]">Benchmarking is based on PAIMANA data.</strong>
              <span className="mt-1 block text-sm leading-6 text-[#263d59]">
                Risk indicators are generated by NIRVAAH for analysed projects only.
              </span>
            </div>
          </div>
        </aside>
      </div>
    </PageHero>
  );
}
