import React from "react";
import { PlayCircle, ShieldCheck } from "lucide-react";
import { Button } from "../ui/Button.jsx";

/**
 * Page introduction for Benchmarking.
 *
 * It keeps the page purpose clear and avoids the dense banner treatment from
 * the reference so users reach the analysis faster.
 */
export function BenchmarkingHero() {
  return (
    <section className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
      <div className="min-w-0">
        <p className="text-sm font-bold text-[#075db7]">Benchmarking</p>
        <h1 className="mt-1 text-3xl font-black leading-tight text-[#052b63] sm:text-4xl" id="benchmarking-title">
          Benchmarking
        </h1>
        <p className="mt-2 max-w-4xl text-base font-semibold leading-7 text-[#526276]">
          Compare cost, schedule, progress and risk across sectors, ministries and peer projects to identify outliers.
        </p>
      </div>
      <Button type="button" variant="secondary" className="w-full lg:w-auto">
        <PlayCircle className="size-4" aria-hidden="true" />
        How Benchmarking Works
      </Button>
      <aside className="rounded-lg border border-[#b9ddff] bg-[#eaf6ff] p-4 lg:col-span-2">
        <div className="grid gap-3 sm:grid-cols-[40px_1fr]">
          <span className="grid size-10 place-items-center rounded-lg bg-white text-[#0b8a7a]">
            <ShieldCheck className="size-5" aria-hidden="true" />
          </span>
          <div className="min-w-0">
            <strong className="block text-sm font-black text-[#052b63]">Benchmarking is based on PAIMANA data.</strong>
            <span className="mt-1 block text-sm leading-6 text-[#263d59]">
              Risk indicators are generated by NIRVAAH for analysed projects only.
            </span>
          </div>
        </div>
      </aside>
    </section>
  );
}
