import { BarChart3, Building2, Clock3, IndianRupee, Landmark, ShieldAlert } from "lucide-react";

// Dummy data for the Projects page.
// When the backend is ready, this file is the first place to replace static
// values with API-shaped data returned from the projects service.

// Portfolio KPI cards displayed above the project workspace.
export const projectKpis = [
  {
    icon: Building2,
    value: "1,775",
    label: "Portfolio",
    note: "Ongoing PAIMANA projects",
    tone: "blue",
    priority: "primary",
  },
  {
    icon: ShieldAlert,
    value: "19",
    label: "Needs Attention",
    note: "Critical or high risk",
    tone: "red",
  },
  {
    icon: IndianRupee,
    value: "₹3.40 L Cr",
    label: "Cost Exposure",
    note: "Above tolerance band",
    tone: "orange",
  },
  {
    icon: BarChart3,
    value: "42",
    label: "Model Coverage",
    note: "Projects with risk scoring",
    tone: "slate",
  },
];

// Project list tabs. The first tab is active in the static prototype.
export const projectTabs = ["Project List", "Map View", "Ministry View", "State View", "Sector View"];

// Filter controls shown in the left panel.
export const projectFilters = [
  { label: "Search", type: "search", placeholder: "Search by project name, ID..." },
  { label: "Ministry", options: ["All Ministries", "Railways", "Jal Shakti", "Housing & Urban Affairs"] },
  { label: "Sector", options: ["All Sectors", "Transport", "Water Resources", "Energy", "Urban Development"] },
  { label: "Project Status", options: ["All", "Ongoing", "Delayed", "Completed"] },
  { label: "Risk Level", options: ["All", "Critical", "High", "Moderate", "Low"] },
];

// Project rows for the main table. The selected project panel uses the first row.
export const projects = [
  {
    id: "PRJ-2025-014",
    name: "Eastern Freight Corridor",
    ministry: "Railways",
    state: "Uttar Pradesh",
    sector: "Transport",
    originalCost: "67,432",
    revisedCost: "72,918",
    expenditure: "28,341",
    progress: 58,
    risk: "Critical",
    riskScore: 91,
    warnings: 3,
    status: "Ongoing",
    costCondition: "+₹5,486 Cr",
    scheduleCondition: "+14 mo",
    lastUpdate: "21 Aug 2026",
    recommendedAction: "Agency review",
    completion: "Mar 2028",
  },
  {
    id: "PRJ-2023-077",
    name: "River Basin Project",
    ministry: "Jal Shakti",
    state: "Bihar",
    sector: "Water Resources",
    originalCost: "12,860",
    revisedCost: "16,245",
    expenditure: "6,982",
    progress: 42,
    risk: "High",
    riskScore: 84,
    warnings: 2,
    status: "Ongoing",
    costCondition: "+₹3,385 Cr",
    scheduleCondition: "+9 mo",
    lastUpdate: "19 Aug 2026",
    recommendedAction: "Cost review",
    completion: "Dec 2027",
  },
  {
    id: "PRJ-2024-201",
    name: "Metro Rail Phase II",
    ministry: "Housing & Urban Affairs",
    state: "Maharashtra",
    sector: "Urban Development",
    originalCost: "48,912",
    revisedCost: "56,230",
    expenditure: "20,114",
    progress: 36,
    risk: "High",
    riskScore: 81,
    warnings: 2,
    status: "Ongoing",
    costCondition: "+₹7,318 Cr",
    scheduleCondition: "+11 mo",
    lastUpdate: "18 Aug 2026",
    recommendedAction: "Milestone review",
    completion: "Aug 2028",
  },
  {
    id: "PRJ-2022-333",
    name: "Coastal Protection Works",
    ministry: "Earth Sciences",
    state: "Tamil Nadu",
    sector: "Water Resources",
    originalCost: "8,541",
    revisedCost: "10,002",
    expenditure: "3,221",
    progress: 28,
    risk: "High",
    riskScore: 79,
    warnings: 2,
    status: "Ongoing",
    costCondition: "+₹1,461 Cr",
    scheduleCondition: "+8 mo",
    lastUpdate: "17 Aug 2026",
    recommendedAction: "Verify progress",
    completion: "Nov 2027",
  },
  {
    id: "PRJ-2024-118",
    name: "National Highway Project",
    ministry: "Road Transport & Highways",
    state: "Karnataka",
    sector: "Transport",
    originalCost: "25,670",
    revisedCost: "31,220",
    expenditure: "11,504",
    progress: 46,
    risk: "Moderate",
    riskScore: 67,
    warnings: 1,
    status: "Ongoing",
    costCondition: "+₹5,550 Cr",
    scheduleCondition: "+6 mo",
    lastUpdate: "16 Aug 2026",
    recommendedAction: "Track land issue",
    completion: "Jun 2028",
  },
  {
    id: "PRJ-2023-089",
    name: "Renewable Energy Park",
    ministry: "New & Renewable Energy",
    state: "Rajasthan",
    sector: "Energy",
    originalCost: "14,980",
    revisedCost: "18,102",
    expenditure: "7,441",
    progress: 52,
    risk: "Moderate",
    riskScore: 59,
    warnings: 1,
    status: "Ongoing",
    costCondition: "+₹3,122 Cr",
    scheduleCondition: "+4 mo",
    lastUpdate: "15 Aug 2026",
    recommendedAction: "Monitor spend",
    completion: "Jan 2027",
  },
  {
    id: "PRJ-2025-301",
    name: "Urban Transport Project",
    ministry: "Housing & Urban Affairs",
    state: "Madhya Pradesh",
    sector: "Urban Development",
    originalCost: "22,410",
    revisedCost: "27,880",
    expenditure: "9,120",
    progress: 31,
    risk: "High",
    riskScore: 76,
    warnings: 2,
    status: "Ongoing",
    costCondition: "+₹5,470 Cr",
    scheduleCondition: "+12 mo",
    lastUpdate: "14 Aug 2026",
    recommendedAction: "Escalate delay",
    completion: "Sep 2028",
  },
  {
    id: "PRJ-2024-066",
    name: "Green Energy Transmission",
    ministry: "Power",
    state: "Gujarat",
    sector: "Energy",
    originalCost: "38,220",
    revisedCost: "41,910",
    expenditure: "16,004",
    progress: 64,
    risk: "Low",
    riskScore: 32,
    warnings: 0,
    status: "Ongoing",
    costCondition: "+₹3,690 Cr",
    scheduleCondition: "On track",
    lastUpdate: "13 Aug 2026",
    recommendedAction: "Maintain watch",
    completion: "May 2027",
  },
  {
    id: "PRJ-2023-190",
    name: "Irrigation Modernisation",
    ministry: "Agriculture",
    state: "Andhra Pradesh",
    sector: "Water Resources",
    originalCost: "11,320",
    revisedCost: "14,650",
    expenditure: "5,888",
    progress: 39,
    risk: "Moderate",
    riskScore: 62,
    warnings: 1,
    status: "Ongoing",
    costCondition: "+₹3,330 Cr",
    scheduleCondition: "+7 mo",
    lastUpdate: "12 Aug 2026",
    recommendedAction: "Review scope",
    completion: "Feb 2028",
  },
  {
    id: "PRJ-2022-501",
    name: "Port Connectivity Project",
    ministry: "Ports, Shipping & Waterways",
    state: "Odisha",
    sector: "Transport",
    originalCost: "19,760",
    revisedCost: "22,430",
    expenditure: "8,118",
    progress: 47,
    risk: "Moderate",
    riskScore: 55,
    warnings: 1,
    status: "Ongoing",
    costCondition: "+₹2,670 Cr",
    scheduleCondition: "+5 mo",
    lastUpdate: "11 Aug 2026",
    recommendedAction: "Check contracts",
    completion: "Oct 2027",
  },
];

// Selected project detail shown in the right-side panel.
export const selectedProject = {
  ...projects[0],
  keyRiskReason: "Physical progress stagnant for 2 reporting periods.",
  warningSummary: "Progress stagnation is now paired with rising cost exposure and delayed milestone closure.",
  recommendedIntervention: "Convene implementing-agency review, verify physical-progress evidence, and require a revised milestone recovery plan.",
  evidence: [
    "Physical progress remains at 58% for two reporting periods.",
    "Revised cost is ₹5,486 Cr above original approved cost.",
    "Completion has shifted to Mar 2028 with a +14 month schedule condition.",
  ],
  actions: ["Open intelligence view", "Add to Watchlist"],
};

// Insight cards under the table summarizing the current filtered view.
export const projectInsights = [
  {
    icon: ShieldAlert,
    value: "12",
    text: "High or Critical Risk Projects in current view",
    tone: "red",
  },
  {
    icon: Building2,
    value: "28%",
    text: "are in the Transport sector",
    tone: "purple",
  },
  {
    icon: Clock3,
    value: "3 projects",
    text: "show progress stagnation across two periods",
    tone: "orange",
  },
  {
    icon: Landmark,
    value: "5 projects",
    text: "have revised completion dates by more than 12 months",
    tone: "green",
  },
];

// Kept for the pulled placeholder component, even though the full dashboard is
// now the active Projects page.
export const projectsPlaceholder = {
  title: "Projects workspace",
  description:
    "This route is reserved for the project list and detail workflows. It keeps Command Centre links usable while we build the next module.",
  ctaLabel: "Back to Command Centre",
  ctaHref: "/nirvaah/command-centre",
};
