import { BarChart3, Building2, Clock3, Cpu, IndianRupee, Landmark, ShieldAlert } from "lucide-react";

// Dummy data for the Projects page.
// When the backend is ready, this file is the first place to replace static
// values with API-shaped data returned from the projects service.

// Portfolio KPI cards displayed above the project workspace.
export const projectKpis = [
  {
    icon: Building2,
    value: "1,775",
    label: "Total Projects",
    note: "Ongoing · PAIMANA July 2026",
    tone: "blue",
  },
  {
    icon: Landmark,
    value: "17",
    label: "Ministries / Departments",
    note: "Central sector coverage",
    tone: "blue",
  },
  {
    icon: IndianRupee,
    value: "₹33.70 L Cr",
    label: "Original Cost",
    note: "Source: PAIMANA",
    tone: "orange",
  },
  {
    icon: IndianRupee,
    value: "₹37.10 L Cr",
    label: "Revised Cost",
    note: "Source: PAIMANA",
    tone: "red",
  },
  {
    icon: BarChart3,
    value: "₹19.26 L Cr",
    label: "Expenditure",
    note: "Cumulative spend",
    tone: "green",
  },
  {
    icon: Cpu,
    value: "42",
    label: "Analysed Projects",
    note: "Generated by NIRVAAH",
    tone: "purple",
  },
];

// Project list tabs. The first tab is active in the static prototype.
export const projectTabs = ["Project List", "Map View", "Ministry View", "State View", "Sector View"];

// Filter controls shown in the left panel.
export const projectFilters = [
  { label: "Search", type: "search", placeholder: "Search by project name, ID..." },
  { label: "Ministry", options: ["All Ministries", "Railways", "Jal Shakti", "Housing & Urban Affairs"] },
  { label: "Sector", options: ["All Sectors", "Transport", "Water Resources", "Energy", "Urban Development"] },
  { label: "State", options: ["All States", "Uttar Pradesh", "Bihar", "Maharashtra", "Karnataka"] },
  { label: "Project Status", options: ["All", "Ongoing", "Delayed", "Completed"] },
  { label: "Risk Level", options: ["All", "Critical", "High", "Moderate", "Low"] },
  { label: "Cost Range", options: ["All", "Below ₹10,000 Cr", "₹10,000-₹50,000 Cr", "Above ₹50,000 Cr"] },
  { label: "Completion Year", options: ["All", "2026", "2027", "2028", "2029+"] },
];

// Project rows for the main table. The selected project panel uses the first row.
export const projects = [
  {
    id: "PRJ-2025-014",
    name: "Eastern Freight Corridor",
    ministry: "Railways",
    state: "Uttar Pradesh",
    sector: "Transport",
    originalCost: "67,432",
    revisedCost: "72,918",
    expenditure: "28,341",
    progress: 58,
    risk: "Critical",
    status: "Ongoing",
    completion: "Mar 2028",
  },
  {
    id: "PRJ-2023-077",
    name: "River Basin Project",
    ministry: "Jal Shakti",
    state: "Bihar",
    sector: "Water Resources",
    originalCost: "12,860",
    revisedCost: "16,245",
    expenditure: "6,982",
    progress: 42,
    risk: "High",
    status: "Ongoing",
    completion: "Dec 2027",
  },
  {
    id: "PRJ-2024-201",
    name: "Metro Rail Phase II",
    ministry: "Housing & Urban Affairs",
    state: "Maharashtra",
    sector: "Urban Development",
    originalCost: "48,912",
    revisedCost: "56,230",
    expenditure: "20,114",
    progress: 36,
    risk: "High",
    status: "Ongoing",
    completion: "Aug 2028",
  },
  {
    id: "PRJ-2022-333",
    name: "Coastal Protection Works",
    ministry: "Earth Sciences",
    state: "Tamil Nadu",
    sector: "Water Resources",
    originalCost: "8,541",
    revisedCost: "10,002",
    expenditure: "3,221",
    progress: 28,
    risk: "High",
    status: "Ongoing",
    completion: "Nov 2027",
  },
  {
    id: "PRJ-2024-118",
    name: "National Highway Project",
    ministry: "Road Transport & Highways",
    state: "Karnataka",
    sector: "Transport",
    originalCost: "25,670",
    revisedCost: "31,220",
    expenditure: "11,504",
    progress: 46,
    risk: "Moderate",
    status: "Ongoing",
    completion: "Jun 2028",
  },
  {
    id: "PRJ-2023-089",
    name: "Renewable Energy Park",
    ministry: "New & Renewable Energy",
    state: "Rajasthan",
    sector: "Energy",
    originalCost: "14,980",
    revisedCost: "18,102",
    expenditure: "7,441",
    progress: 52,
    risk: "Moderate",
    status: "Ongoing",
    completion: "Jan 2027",
  },
  {
    id: "PRJ-2025-301",
    name: "Urban Transport Project",
    ministry: "Housing & Urban Affairs",
    state: "Madhya Pradesh",
    sector: "Urban Development",
    originalCost: "22,410",
    revisedCost: "27,880",
    expenditure: "9,120",
    progress: 31,
    risk: "High",
    status: "Ongoing",
    completion: "Sep 2028",
  },
  {
    id: "PRJ-2024-066",
    name: "Green Energy Transmission",
    ministry: "Power",
    state: "Gujarat",
    sector: "Energy",
    originalCost: "38,220",
    revisedCost: "41,910",
    expenditure: "16,004",
    progress: 64,
    risk: "Low",
    status: "Ongoing",
    completion: "May 2027",
  },
  {
    id: "PRJ-2023-190",
    name: "Irrigation Modernisation",
    ministry: "Agriculture",
    state: "Andhra Pradesh",
    sector: "Water Resources",
    originalCost: "11,320",
    revisedCost: "14,650",
    expenditure: "5,888",
    progress: 39,
    risk: "Moderate",
    status: "Ongoing",
    completion: "Feb 2028",
  },
  {
    id: "PRJ-2022-501",
    name: "Port Connectivity Project",
    ministry: "Ports, Shipping & Waterways",
    state: "Odisha",
    sector: "Transport",
    originalCost: "19,760",
    revisedCost: "22,430",
    expenditure: "8,118",
    progress: 47,
    risk: "Moderate",
    status: "Ongoing",
    completion: "Oct 2027",
  },
];

// Selected project detail shown in the right-side panel.
export const selectedProject = {
  ...projects[0],
  keyRiskReason: "Physical progress stagnant for 2 reporting periods.",
  actions: ["View Project", "Add to Watchlist"],
};

// Insight cards under the table summarizing the current filtered view.
export const projectInsights = [
  {
    icon: ShieldAlert,
    value: "12",
    text: "High or Critical Risk Projects in current view",
    tone: "red",
  },
  {
    icon: Building2,
    value: "28%",
    text: "are in the Transport sector",
    tone: "purple",
  },
  {
    icon: Clock3,
    value: "3 projects",
    text: "show progress stagnation across two periods",
    tone: "orange",
  },
  {
    icon: Landmark,
    value: "5 projects",
    text: "have revised completion dates by more than 12 months",
    tone: "green",
  },
];

// Suggested assistant prompts for the Projects page.
export const projectAssistantPrompts = [
  "Which projects need immediate attention?",
  "Show transport projects with high risk",
  "Why is Eastern Freight Corridor critical?",
];
