import React from "react";
import { MapPin, Megaphone } from "lucide-react";
import { Button } from "../ui/Button.jsx";

/**
 * Top introduction for the Projects page.
 *
 * It tells officers what the workspace is for and repeats the source of risk
 * scoring so the page feels transparent.
 */
export function ProjectPageHeader() {
  return (
    <section className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(300px,0.75fr)_auto] lg:items-center">
      <div className="min-w-0">
        <p className="text-sm font-bold text-[#075db7]">Projects</p>
        <h1 className="mt-1 text-3xl font-black leading-tight text-[#052b63] sm:text-4xl" id="projects-title">
          All Infrastructure Projects
        </h1>
        <span className="mt-2 block text-base font-semibold leading-7 text-[#526276]">
          Explore, search and analyse India's major infrastructure projects.
        </span>
      </div>
      <aside className="grid min-w-0 gap-3 rounded-lg border border-[#b9ddff] bg-[#eaf6ff] p-4 sm:grid-cols-[40px_1fr]">
        <span className="grid size-10 place-items-center rounded-lg bg-white text-[#0b8a7a]">
          <Megaphone className="size-5" aria-hidden="true" />
        </span>
        <div className="min-w-0">
          <strong className="block text-sm font-black text-[#052b63]">Data from PAIMANA. Risk assessment generated by NIRVAAH.</strong>
          <span className="mt-1 block text-sm leading-6 text-[#263d59]">
            Use filters, search or saved views to identify projects needing attention.
          </span>
        </div>
      </aside>
      <Button type="button" variant="secondary" className="w-full lg:w-auto">
        <MapPin className="size-4" aria-hidden="true" />
        View on Map
      </Button>
    </section>
  );
}
